###

GET http://localhost:8080/user/material-requests?status=ALL&dateFrom=2025-01-01&dateTo=2026-01-01
Authorization: bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUFJPRFVDVElPTl9VU0VSIiwidXNlcklkIjoiUFJPRFVDVElPTl9VU0VSIiwiZW1haWwiOiJwcm9kdWN0aW9uQGNvbXBhbnkuY29tIiwic3ViIjoicHJkMSIsImlhdCI6MTczNzQ2MjIyMywiZXhwIjoxNzM3NDY0MDIzfQ.H_rLJAkO-3Sbv-mr4f4FhKNGbO8mbZCitsjMpPih30k
 
GET http://localhost:8080/admin/material-requests?status=ALL&dateFrom=2025-01-01&dateTo=2026-01-01
Cookie: jwtToken=eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiV0FSRUhPVVNFX0FETUlOIiwidXNlcklkIjoiV0FSRUhPVVNFX0FETUlOIiwiZW1haWwiOiJ3YXJlaG91c2VAY29tcGFueS5jb20iLCJzdWIiOiJ3aDEiLCJpYXQiOjE3MzcxNzI0NDgsImV4cCI6MTczNzE3NDI0OH0.KspThtb0tltjCxy4J___el4rgh9_bjCPkRzEExA-DFg; Max-Age=604800; Expires=Sat, 25 Jan 2025 03:54:08 GMT; Path=/; Secure; HttpOnly


###
GET http://localhost:8080/material-request?requestId=16
Cookie: jwtToken=eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUFJPRFVDVElPTl9VU0VSIiwidXNlcklkIjoiUFJPRFVDVElPTl9VU0VSIiwiZW1haWwiOiJQUk9EVUNUSU9OX1VTRVIiLCJzdWIiOiJ3aDEiLCJpYXQiOjE3MzcxNjUyMzIsImV4cCI6MTczNzE2NzAzMn0.SoPv-TiXCfyU_RQTFcbXDA9akJ2_AhAY48JQVLW6u9g; Max-Age=604800; Expires=Sat, 25 Jan 2025 01:53:52 GMT; Path=/; Secure; HttpOnly

###
DELETE http://localhost:8080/material-request?requestId=2


###
POST http://localhost:8080/material-request
Content-Type: application/json

{
    "items": [
        { "materialName": "karung", "requestedQuantity": 50, "usageDescription":" packaging big waste" },
        { "materialName": "trash bag", "requestedQuantity": 150, "usageDescription":"packaging medium waste" },
        { "materialName": "plastik", "requestedQuantity": 500, "usageDescription":"packaging small waste" }
    ]
}

###
PUT http://localhost:8080/material-request
Content-Type: application/json

{
    "requestId":16,
    "items": [
        { "itemId":6, "materialName": "updated karung", "requestedQuantity": 1000, "usageDescription":"updated packaging big waste" },
        { "itemId":7, "materialName": "updated trash bag", "requestedQuantity": 1000, "usageDescription":"updated packaging medium waste" },
        { "itemId":8, "materialName": "updated plastik", "requestedQuantity": 1000, "usageDescription":"updated packaging small waste" }
    ]
}


###############################################
POST http://localhost:8080/material-request-item
Content-Type: application/json

{ 
    "requestId": 16,
    "materialName": "(v4)material baru", 
    "requestedQuantity": 777, 
    "usageDescription":"(v4)material baru desc" 
}


###
PUT http://localhost:8080/material-request-item
Content-Type: application/json

{ 
    "requestId": 16,
    "itemId":9, 
    "materialName": "berubah", 
    "requestedQuantity": 1200, 
    "usageDescription":"seharusnya aman" 
}


###
 DELETE http://localhost:8080/material-request-item?requestId=16&itemId=10


###############################################

GET http://localhost:8080
//Cookie: jwtToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwcmQxIiwiaWF0IjoxNzM3MDk0NjkzLCJleHAiOjE3MzcwOTY0OTN9.cTZ6MKpREjWtf5wakPuo4J4nOEtJVABtfSdNtSa5vCU; Max-Age=604800; Expires=Fri, 24 Jan 2025 06:18:13 GMT; Path=/; Secure; HttpOnly

###

POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "userId": "prd1",
    "password": "production123"
}

###

POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "userId": "wh1",
    "password": "warehouse123"
}

